[tools]
node = "24"

[hooks]
postinstall = "npx corepack enable"

[settings]
experimental = true

[env]
_.path = ['./node_modules/.bin']

[tasks.pnpm-install]
description = "Install dependencies using pnpm"
run = "pnpm install"
sources = ["package.json", "pnpm-lock.yaml", "mise.toml"]
outputs = ["node_modules/.pnpm/lock.yaml"]
